name: Build DragonMiner MFC Game

on:
  push:
    branches: [master]
  workflow_dispatch:  # ✅ 手动触发支持

jobs:
  build:
    name: Build MFC EXE
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Build with MSBuild
        run: |
          msbuild DragonMiner.sln /p:Configuration=Release /p:Platform=x64

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: DragonMiner-exe
          path: |
            x64/Release/DragonMiner.exe
